### ISSUE TITLE
Missing hog binary doesn't result in error to terminal

### ISSUE THREAD

**Issue by brianegge** [Morgan-Stanley/hobbes#111]
There are no exception handlers, so the code which throws the exception just terminates the process. It would helpful to know that the execv failed because the hog file was missing.

https://github.com/Morgan-Stanley/hobbes/blob/45b68b98aa9891aed8cf09a11aaa557edd495886/test/Hog.C#L131

**Comment by chenkai036** [comment]
Thanks for pointing out!  I'll provide a better error reporting for this.
