### ISSUE TITLE
invoke the ctor for each slot in an array<T>

### ISSUE THREAD

**Issue by salumup** [Morgan-Stanley/hobbes#147]
https://github.com/Morgan-Stanley/hobbes/blob/50819464fa90f16de0a9143f3853948cd369b373/include/hobbes/hobbes.H#L59

Every slot is left uninitialised, which can cause crashes.

**Comment by kthielen** [comment]
Fixed here:

https://github.com/Morgan-Stanley/hobbes/pull/148
