### ISSUE TITLE
doesn't build

### ISSUE THREAD

**Issue by jeb2239** [Morgan-Stanley/hobbes#151]
the master build fails on linux because of the more restrictive compiler flags.

**Comment by kthielen** [comment]
I think that our automated tests are building on Linux (and OSX).  Could you add the OS and compiler details you're testing with, and maybe the first error message?

I am sorry about these more restrictive compiler flags, I know it's very annoying.  Unfortunately we have hobbes integrated with a couple of projects that use these settings, so the easiest way to ensure that it would work was to use the same strictness settings as those projects.

Disallowing C-style casts is the most painful, IMHO.

**Comment by jeb2239** [comment]
This is gcc 7.2 on Ubuntu. There are several old style casts still used on master.

**Comment by kthielen** [comment]
Shoot, it's probably a different LLVM version than we're testing with.  There's probably some conditionally-compiled code that was missed and not tested with automated builds.  What LLVM version are you using?

**Comment by jeb2239** [comment]
llvm 4

**Comment by kthielen** [comment]
Thanks jeb!!  I have got a PR that fixes this build issue here and will guarantee that LLVM4 will always be tested going forward: https://github.com/Morgan-Stanley/hobbes/pull/152

I should have added this test originally, but better late than never! :D
