### ISSUE TITLE
issue with install hobbes in centos 7

### ISSUE THREAD

**Issue by zhangjiahao** [Morgan-Stanley/hobbes#185]
I make and installed quickly in my debian server.However, when comes to Centos 7 . I have tried llvm3.4 ,llvm3.9, llvm5.0 but they all make failed. Sometimes not get the LLVM_VERSION_MINOR;
sometimes miss llvm::createGVNPass() this method,even in llvm5.0, Not such file:llvm/Config/llvm-config.h.I use yum install llvm in Centos.  I am really love this language and want to do some development for analysis data.

**Comment by kthielen** [comment]
Hi Jiahao,

Thank you for your patience.  These LLVM issues are always the hardest part of building and testing.  I haven't tried Centos 7, it's worth looking into.

In general, when you run the cmake step, then you have to provide the path to the LLVM cmake files with the LLVM_DIR environment variable (pointing to where LLVM's cmake files are).

**Comment by kthielen** [comment]
How are you installing llvm?  I just installed Centos 7 on my laptop and it doesn't seem like yum has an llvm package like we install with apt, port, and brew.

I think that we probably have to install llvm from source.

**Comment by libow** [comment]
I suggest you build llvm 3.7.1 from source code and and enable RTTI. It works most of platforms. i tried it on Arch Linux
``` 
LLVM_ENABLE_RTTI:BOOL
  Build LLVM with run-time type information. Defaults to OFF.
```

**Comment by zhangjiahao** [comment]
hi，kthilen.
         if use llvm,You should yum install epel-release first.then you can yum search llvm to see some versions.I will have a try to building llvm3.7.1 myself later.

**Comment by zhangjiahao** [comment]
After building llvm3.7.1 source and comment out this line in . Then installed success.
@@ -533,7 +533,7 @@ void cc::dumpTypeEnv(str::seq* syms, str::seq* types) const {
 }
 std::string cc::showTypeEnv() const {
-  const TEnv::PolyTypeEnv& ptenv = this->tenv->typeEnvTable();
+  //const TEnv::PolyTypeEnv& ptenv = this->tenv->typeEnvTable();

Thank you all very much.

**Comment by kthielen** [comment]
Just out of curiosity, what is the error that you cleared by commenting out that line?

Good job getting llvm to build, that's the hardest part of compiling hobbes ...

**Comment by zhangjiahao** [comment]
set but not used. and all warnings being treated as errors

**Comment by kthielen** [comment]
Thanks for pointing out that error about an unused variable.  I've got a PR going in that fixes it.

Also thanks for working through the LLVM build issue.  We will have to do something at some point to make that easier.

Closing the issue now, since I think we've covered everything here.
