### ISSUE TITLE
hog should block new connections until old disconnected ones are drained

### ISSUE THREAD

**Issue by kthielen** [Morgan-Stanley/hobbes#194]
There is a concern that one producer process might record a series of transactions, crash (or be shut down), then restart, and have transactions recorded out of order between the two (ie: some old transactions, followed by some new transactions, followed by some old transactions).

Instead, we should have hog block new connections until it's confirmed that old disconnected ones are completely finished.

**Comment by chenkai036** [comment]
maybe we could reclaim the reader threads after hog "deactivates" the old shared-memory?

**Comment by kthielen** [comment]
Yes, definitely.
