### ISSUE TITLE
Chat room for hobbes

### ISSUE THREAD

**Issue by jeb2239** [Morgan-Stanley/hobbes#22]
Hello, I was wondering if we could create some sort of chat room for hobbes. This would make separating issues from questions simpler. Gitter.im or Slack is the one most github hosted projects seem to use.

**Comment by kthielen** [comment]
Good idea.  Those won't work inside the MS network but I can try slack on my laptop.

**Comment by kthielen** [comment]
Looks like I can get slack on my phone at least, I've just made the group "hobbes-lang" there.

**Comment by kthielen** [comment]
This is an interesting idea, let me see what I can do.

**Comment by libow** [comment]
do i need invitation to join that group?

**Comment by kthielen** [comment]
There isn't a group yet.  There are still a few issues to sort out before this can be set up.

**Comment by kthielen** [comment]
Having spent some time discussing this internally, I think that starting or contributing to an open Slack channel is not something that we're prepared to do at this time (but may revisit later).  In the meantime, anyone outside of Morgan Stanley can still start such a channel if they'd like.
