### ISSUE TITLE
Example programs

### ISSUE THREAD

**Issue by kthielen** [Morgan-Stanley/hobbes#23]
Any thoughts on the best way to package example programs with the base library?  Arguably the "hi" and "hog" programs are example programs, even though they are used very often for real work.

I'm a little concerned about the way that dependencies might be introduced through these programs.  For example, the "hi" program wants to use readline, so readline has effectively become a dependency of hobbes.  However, somebody could easily use hobbes without needing to use "hi".

I've been considering making some OpenGL example programs and wouldn't want to make OpenGL a dependency of hobbes. ;)

**Comment by jeb2239** [comment]
Cmake supports optional dependencies with find package

**Comment by jeb2239** [comment]
I also think it would be good to have some sort of language syntax examples. Thinks that could server as a base for a language manual later.

**Comment by kthielen** [comment]
With optional dependencies, would we make compilation of "hi" depend on whether readline is present?  I guess I will have to read up on this, I don't actually know much about cmake.

**Comment by jeb2239** [comment]
There are other ways to manage the install of dependencies. For example https://conan.io/  is a C++ package manager kind of like maven. It automatically downloads libraries.

**Comment by jeb2239** [comment]
Also are there coding standards for this project? How important is writing cross platform - cross compilable code. For example I noticed the use of the gnu specific named var args.  According to  https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html


```
Variadic macros became a standard part of the C language with C99. GNU CPP previously supported them with a named variable argument (‘args…’, not ‘…’ and __VA_ARGS__), which is still supported for backward compatibility.

```

**Comment by kthielen** [comment]
Coding standards might become more important in the future, but for the history of this project we (mostly me) have incrementally added code alongside production support mostly in a "forward-only" way and just in the internal environment (with one or two compiler/OS pairings being standard).

It's just recently been updated to support clang/OSX and other variants of Linux.  I am sure that an attempt to port to VC++/Windows would show many portability problems (including the one you raised about naming variadic macro args).

Currently (at least for this issue we're commenting under), I am interested in setting up some kind of structure for including example programs (which don't necessarily build with hobbes as-is but are at least around to build subsequently if necessary).

**Comment by jeb2239** [comment]
You could make programs on your personal github which come with makefiles. Even have a link to them.

**Comment by jeb2239** [comment]
Also not directly related to this but in my fork I have set up github pages for hosting generated docs. https://jeb2239.github.io/hobbes/

I just use this for the class diagram and browsing the code.

**Comment by kthielen** [comment]
Funny coincidence, I was just checking out github pages too!  I started a basic page and I was thinking that maybe this would be the best place to write more detailed articles on use-cases for hobbes.

**Comment by kthielen** [comment]
Also that's really cool that you've got doxygen pages generated.  That should probably be accessible in the official pages site too.

**Comment by jeb2239** [comment]
yup I can do a pull request with the configuration if you are interested. Then all you would need to do is install doxygen locally and cd into hobbes and type `doxygen` and enter.

**Comment by cpehle** [comment]
I've slightly restructured the build system in my [fork](https://github.com/cpehle/hobbes), with that structure it is fairly easy to introduce optional targets based on the availability of them on the system. Unfortunately it does not build on macOS for some reason I don't understand at the moment.

**Comment by kthielen** [comment]
What's wrong with readline? (not combative, honestly curious)

**Comment by cpehle** [comment]
From a perspective of the project the main advantage is that linenoise is small (~1000 lines of code as opposed to 20-30k for the alternatives) and can easily be included as a third party dependency because it has a permissive license. It also fairly straightforward to [use](https://github.com/cpehle/hobbes/blob/master/examples/embedding/embedding.cpp), this is the embedding example using line noise. 

The build issue on macOS was related to the fact that some of the header files have the same name as standard library headers (ctype.H) on case insensitive file systems.

**Comment by kthielen** [comment]
@cpehle that library does look interesting, does it have an incremental mode?  With readline in hi we add stdin to an epoll/kqueue set and incrementally read expressions as the stdin FD update triggers (so that we can service network requests and respond to file updates at the same time).

Also it might be better to raise that question to its own issue, since this one in particular will get closed when the question of how best to package example programs gets closed.

**Comment by cpehle** [comment]
@kthielen: Short answer is no. It is fairly easy to add such a mode though. I've got a version of this (mostly) working [now](https://github.com/cpehle/hobbes/commit/b15e3b6639d07fd0b48db09d334617951803306f), it amounts to adding two new functions to the linenoise library and making the internal context accessible so that it can be handed back in the event handler. But you are right this should probably be discussed in another issue.
