### ISSUE TITLE
Finding equivalent DFA states takes a long time for some large DFA

### ISSUE THREAD

**Issue by chenkai036** [Morgan-Stanley/hobbes#280]
There relevant code is [here](https://github.com/Morgan-Stanley/hobbes/blob/d1ca72e8f61f79a67c4defa167b03ff739f404dd/lib/hobbes/lang/pat/regex.C#L1137)

Once we complete the first round of checking equivalent states, we're not leveraging the equivalence classes we found so far to reduce the loop for the next round.  Instead, the for-loops always run `dfa.size() * dfa.size() / 2` times inside the while-loop.

Perhaps we can use disjoint set for 1) managing equivalence classes of DFA states, e.g. accessing to the representatives and joining two equivalence classes into one; 2) mapping the loop-index to the corresponding DFA index.

**Comment by kthielen** [comment]
Nice one, this would be a good improvement (especially for those cases where this feature gets used often).

I like the tag idea.  Maybe we'll get to distinguish priorities for compiler performance (usually the startup cost) versus generated code performance (the critical path).

**Comment by chenkai036** [comment]
> I like the tag idea. Maybe we'll get to distinguish priorities for compiler performance (usually the startup cost) versus generated code performance (the critical path).

Thanks for the suggestions, I've updated the label :P
