### ISSUE TITLE
re-definitions of "TestVariant" in testcases

### ISSUE THREAD

**Issue by chenkai036** [Morgan-Stanley/hobbes#288]
`TestVariant` has been defined twice in [Hog.C](https://github.com/Morgan-Stanley/hobbes/blob/18aa28d1e965cc2a190fa38486ca6284b98960cb/test/Hog.C#L491) and [Python.C](https://github.com/Morgan-Stanley/hobbes/blob/18aa28d1e965cc2a190fa38486ca6284b98960cb/test/Python.C#L71), but with different types as its members.

**Comment by kthielen** [comment]
Is it bad that they're different?  Although they have the same name, they're not actually related -- they're completely independent.  The Python.C code verifies that the fregion.py script can read structured file data correctly but the data that it verifies is generated from C++ inside Python.C.
