### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Morgan-Stanley/hobbes#32]
I would like to point out that identifiers like “[`_HOBPP_FIRST`](https://github.com/Morgan-Stanley/hobbes/blob/8b75fcf9c0552954701a141bf67348739e015afa/include/hobbes/util/preprocessor.H#L10 "Update candidate")” and “[`_HSTORE_STATE_UNBLOCKED`](https://github.com/Morgan-Stanley/hobbes/blob/ed194c3948c72a72483a417f48b0b02292f58e17/include/hobbes/storage.H#L241 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by kthielen** [comment]
What would you suggest?

**Comment by elfring** [comment]
I suggest to [delete misplaced underscores in affected identifiers](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").

**Comment by kthielen** [comment]
Fair enough, pretty simple change.  I will link back with a PR to resolve this and keep the issue open until that's done.  Thanks.

**Comment by kthielen** [comment]
Renaming applied in this PR: https://github.com/Morgan-Stanley/hobbes/pull/38

**Comment by elfring** [comment]
Were [a few update candidates left over](https://github.com/Morgan-Stanley/hobbes/blob/8b75fcf9c0552954701a141bf67348739e015afa/include/hobbes/util/preprocessor.H#L10 "Update candidate: _HOBPP")?
