### ISSUE TITLE
Build stuck running tests on NixOS

### ISSUE THREAD

**Issue by thmzlt** [Morgan-Stanley/hobbes#329]
I'm trying to add a hobbes derivation to the nixpkgs package collection, but the build is stuck (and timing out) when running the tests. I tried it locally on NixOS and it indeed doesn't move past the first test.

https://github.com/NixOS/nixpkgs/pull/79699/checks?check_run_id=436141813

Any hints on how I can approach this?

**Comment by kthielen** [comment]
Doh, so close!  I think that it might be saying "the first test" here when it just means the whole test suite.  We build a program called "hobbes-test" that runs a bunch of tests (with console output).  I bet that running this program directly would reveal which test is getting stuck and my bet is that it'll be the hog tests.

I think that I have a nixOS VM on my home laptop, maybe I can try to reproduce this there.

Actually, I wonder why we aren't hitting this with the travis-ci build that you helped us add.  That uses the same nix script to build hobbes doesn't it?  Maybe it's not running the tests but just building everything ...

**Comment by kthielen** [comment]
Just checked e.g. here, it does seem that these tests run under travis-ci for the nix build target:
https://travis-ci.org/Morgan-Stanley/hobbes/jobs/636889939?utm_medium=notification&utm_source=github_status

Maybe something is different under nixOS though.  Probably I will need to look at it, unless you've got a really high pain threshold.  :D

**Comment by thmzlt** [comment]
Right. I checked the Travis build too. I think Travis uses Nix (the package manager) and not NixOS (the distribution). I know that NixOS builds packages using a daemon for its multi-user environment, so maybe it's related to that.

**Comment by thmzlt** [comment]
Just tested the NixOS build again with 8f920f320223f301a3e732e478a2facafd94687a, and it still gets stuck on hobbes-test when the doCheck flag is enabled. I assumed only the hog tests would be skipped.

Let me know when you want me to update the PR on nixpkgs.

**Comment by kthielen** [comment]
Darn, maybe this is down to all of the filesystem testing that we do in hobbes-test, which seems not to work under nix install where the build directory gets unlinked in the background.

I will open a PR to disable these tests under nix for now, I guess that's just a change I need to make to the project's default.nix script?

**Comment by kthielen** [comment]
Actually in the last merge, `doCheck` was set to `false`.  Is that not enough to avoid going through these tests for the nix install?

**Comment by thmzlt** [comment]
Yes, that should be enough. I was wondering if you wanted to skip all tests or just the ones related to the filesystem. If we're skipping all tests, it should be :+1:.

**Comment by kthielen** [comment]
For now, given the number of tests affected by the nix build's unlinking of temporary build directories, and the newness of the nixOS distribution channel (for this project), it seems like a reasonable approach.

**Comment by bhipple** [comment]
On the nix front, to debug hanging tests, if you have root on your machine see the `breakpointHook` documentation:

https://nixos.org/nixpkgs/manual/#ssec-setup-hooks

This will let you exec into the build container once it fails using [cntr](https://github.com/Mic92/cntr).

**Comment by kthielen** [comment]
Thanks @bhipple, I guess the way that nixos runs these tests breaks a few assumptions in the way we've been running these tests so far.  I think this still isn't the primary channel that hobbes is distributed through but it seems like it'll only become more important so I'll have to figure this out eventually.

I guess the main issue right now is that our nix setup uses gcc6, but gcc8/gcc9 are current.  I thought we were compiling on gcc8 already but I'll see if I can figure this out tomorrow.

**Comment by smunix** [comment]
Addressed in #380, closing this ticket
