### ISSUE TITLE
Test Result

### ISSUE THREAD

**Issue by skaller** [Morgan-Stanley/hobbes#34]
Probably the build instructions should include

```
make test
```

I tries that and got this:

```
~/Desktop/hobbes>make test
Running tests...
Test project /Users/skaller/Desktop/hobbes
    Start 1: hobbes-test
1/1 Test #1: hobbes-test ......................***Exception: Other 23.11 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  23.12 sec

The following tests FAILED:
	  1 - hobbes-test (OTHER_FAULT)
Errors while running CTest
make: *** [test] Error 8
```

Any idea what's happening?

**Comment by kthielen** [comment]
Good idea to add that to the build instructions.  The CI build does run hobbes-test as part of its validation process.  It's hard to know what happened there given the way that the output is handled (maybe a cmake decision to suppress output?).  If you run the hobbes-test program directly, you should get a better answer.  If you're using LLVM 4.0+ but don't have the PR I submitted for that change, there might be an error you hit on the 'pattern match machine code efficiency' check.

**Comment by skaller** [comment]
I found this log of the test:

[log.txt](https://github.com/Morgan-Stanley/hobbes/files/1176943/log.txt)

**Comment by kthielen** [comment]
Yes I also encountered that same error and verified a fix with the code I checked in to support LLVM 4.0.  Could you pull master and try again?

That reminds me, I need to update the Travis CI job to verify more versions of LLVM (including 4.0 now).

**Comment by skaller** [comment]
Ah .. I get a problem

```
error: Your local changes to the following files would be overwritten by merge:
	include/hobbes/eval/jitcc.H
	include/hobbes/util/llvm.H
	lib/hobbes/eval/jitcc.C
Please commit your changes or stash them before you merge.
```

because I manually modified some files *before* applying your patch. Is the patch now included in the repository?

**Comment by kthielen** [comment]
If your local modifications add checks for the LLVM version major value then yes those changes are incorporated in master now.

The particular LLVM exception you hit is fixed in jitcc.C and has to do with a minor change they made to an API for one of their "optional string" types, for what it's worth.

**Comment by skaller** [comment]
OK, rebuilding. I reset my repo.The hobbes tests now pass. However the Felix binding now fails!

```
~/felix>flx hint.flx
: CommandLine Error: Option 'debug-buffer-size' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

For dynamic linkage. On the other hand, the static link Felix binding works.

```
flx --static hint.flx
... lots of linker warnings ..
... test program now runs correctly ..
```

except it spews lots of those linker error lines. So this is probably a linker related issue,
whatever is registering options is duplicated, and the duplicates are not being eliminated,
leading to the same thing being called twice. This is a typical problem with non-reentrant
code in C++ that uses global variables with non-trivial constructors that do things
such as attempt to initialise something. C++ says the variable should only occur once,
but that doesn't work with dynamic linkage unless the exact right linkage is applied
to the variable. The solution is to do the initialisation "reentrantly", that is, in the top 
level function (mainline). If the system has several parts, they should communicate
with an explicit handle, and the handle constructor then does the initialisation.

If you're dealing with a non-reentrant library all hell breaks loose. Then you have
to get the linkage right. Or you can cheat: you do the initialisation and set a variable
to indicate it is done, so if you're called again you don't do it twice. The problem with that
is it assumes you succeeded in getting only one copy of the variable. The standard
C++ trick is to use a static variable local to the function itself, and rely on there
being only one copy of the function. Linkers handle uniqueness of functions better
than uniqueness of data.

**Comment by skaller** [comment]
[SIDE NOTE: the makefile cmake generates is BUGGED!
I mean it completely fails to check dependencies. I can change a file,
run make, and it doesn't recompile anything. I have to "make clean"
every time .. ugggh]

So I did this:

```
~/Desktop/hobbes>grep -r buffer-size .
Binary file ./hi matches
Binary file ./hobbes-test matches
Binary file ./hog matches
```

The relevant string is indeed in the three binaries .. but not in any of the source code,
at least not intact. I also scanned cmake files used for LLVM linkage with no luck.

Since the problem only occurred after recent changes, I had a look at the github commit list.
The one I pick as indicative is this one:

```
b56e0cef80f8b2310e31da33aac64df46194dd95
few minor changes to work with LLVM 4.0 (#31)
...
 inline llvm::LLVMContext& context() {
 -  return llvm::getGlobalContext();
 +  static llvm::LLVMContext ctx;
 +  return ctx;
  }
```

because it is clearly a linkage related change, and related to LLVM. The patch above
changes from dynamically fetching the (stupidly nonreentrant) LLVM context,
to using a function with a local static variable. This means C++ is trying to ensure there
is only one copy of the variable with some trickery. 

The same kind of error is noted here:

https://bugzilla.redhat.com/show_bug.cgi?id=1309055

A comment says:
```
I think the clang is linked incorrectly.

It looks like the problem appeared quickly after switching to single libLLVM.so.
```

There is also a comment:

```
The llvm-static is just due to stupid llvm cmake scripts looking for some stuff, try building without llvm-static involved and see what falls out.
```

A bit more here:
```
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/I56FXPM33TNHTXPR32CONH57AUIKUU6D/
```

Looks like a possible bug in LLVM rather than hobbes. However the underlying cause
is the same:  C programmers that have not been taught what reentrancy is about.

The problem is .. the previous build I did didn't have this problem and the patch above
must have already been done (because getGlobalContext isn't defined in LLVM4).

**Comment by kthielen** [comment]
Yeah, I'm not happy with the complex build either.  I'd rather just have a single makefile, self-contained library.  At some point, maybe it's easier to just write our own back-end.  :)

That particular excerpt you quoted was recently changed for the LLVM 4.0 support (I did the commit but it wasn't my idea to change it that way).  I wonder if it would work just as well with `llvm::getGlobalContext()` or was it necessary to make this a local static variable?

**Comment by skaller** [comment]
I tried (manually) reverting, but getGlobalContext is no longer available it seems. At least, I got a compile time error. The interface declaring a non-initialised variable baffles me. I tried to initialise it but couldn't figure out how to do it in C++. The type isn't copyable, but i got an absurd error from clang if I wrote

```
llvm::LLVMContext ctx();
```
It told me llvm::LLVMContext wasn't compatible with type llvm::LLVMContext. What rubbish!

I was just trying to figure out what changed between my old sources of hobbes, which had been patched, and the new copy direct from the repository without changes. Because the old one worked with dynamic linkage. The new one doesn't. I can static link, it works, but I get horrible linker messages and I prefer to use Felix with dynamic linkage to run scripts (that's the default).

My logical explanation is that somehow there are two ctx objects where previously there was one, but I can't figure out why. In Felix I use a heap allocated hobbes::cc object. This WILL create an hobbes::cc object every call, but I only call it once. Not clear how hobbes::cc related to llvm context object though.

So its possible the problem is that because my Felix code is in a shared library, its not actually sharing the inline function llvm::getContext. in other words there are actually TWO ctx variables: one is in the Felix generated shared library and one in hobbes shared library. This is easy to fix, just make it non-inline function in some translation unit.

My difficulty is that I can't see how this has changed from the previous build. Although the change in the commit is only 3 days old, after the last build, the code I build previously was patched exactly the same as the commit modification (except for the spelling of the name of the context variable :)

If llvm::getContext were to be out of line, which translation unit would you put it in? I don't want a new one because that would require changing some build scripts (rather climb Everest without O2 than try that). If it then a plain extern interface, that would ensure only one copy of ctx. No point changing the repo until I can test if this is related to the problem.

**Comment by kthielen** [comment]
Maybe try putting the global llvm::LLVMContext in hobbes/eval/jitcc.C?  If that clears up the error, it'd be the reasonable place to put it.

**Comment by skaller** [comment]
Ok thanks, I tried that. It doesn't fix the problem.

**Comment by skaller** [comment]
Ok, but the bug is still in there somewhere. Probably it is in LLVM.

**Comment by kthielen** [comment]
We are doing a bit of internal work, and going forward I want to have our issue list reflect work that we're actually doing.
