### ISSUE TITLE
Datetimes and times with negative representation don't display properly

### ISSUE THREAD

**Issue by adam-antonik** [Morgan-Stanley/hobbes#340]
A very minor but annoying issue

    > 1960-01-01T01:01:01.123456
    1960-01-01T01:01:02.-876544

Solving this seems to just need something like the following added to showDateTime

    inline std::string showDateTime(long x) {
      int64_t s  = x / (1000L * 1000L);
      int64_t us = x % (1000L * 1000L);
    
      if (us < 0) {
        s -= 1;
        us += 1000L * 1000L;
      }
      [...]
    }

Similarly for showTime.

**Comment by kthielen** [comment]
Oops, thank you!  I can put in a PR later.  :)

**Comment by adam-antonik** [comment]
If you're going to threaten me like that, then whilst you're there:
   > 01:01:02.123
   01:01:02.000123

TTIME and TDATETIME both allow 3 digits after the dot, but still parse it as microseconds.  'u' needs to be multiplied by 1000 if s_u.second has length 3.

**Comment by kthielen** [comment]
Good catch.  >_<

**Comment by kthielen** [comment]
I unintentionally pushed these changes to an existing PR, but I think they're small enough to go in anyway (the PR in question is also very minor):

https://github.com/Morgan-Stanley/hobbes/pull/339

**Comment by kthielen** [comment]
These two fixes were merged to master.
