### ISSUE TITLE
Two syntax annoyances with indents in class/instance

### ISSUE THREAD

**Issue by adam-antonik** [Morgan-Stanley/hobbes#347]
First, trailing whitespace after a class or instance definition is interpreted as an indent, this causes an error if it reaches the end, or worse, interprets the next non-indented line as being a cmember or imember.  Does the following modification to line 71 of hexpr.l make sense?

    "\n"[ \t]+/([^ \t\n/]|"/"[^*/])                  { yycolumn = 2; if (wantIndent()) { return TINDENT; }

i.e. if new line followed by whitespace and looking ahead there is something not a comment on that line, then indent.  This means one cant prefix one's class or instance declaration with a block comment, but that would be ugly anyway ;)

Secondly, if one tries to write a multiline instance, then one can't use indentation, which hurts readability.  I think we can do a slight modification to the indent logic with

    std::vector<int> yyIndentStack;
    void pushIndent() {
      yyIndentStack.push_back(yyWantIndent);
      yyWantIndent = 0;
    }
    
    void popIndent() {
      if(!yyIndentStack.empty()){
        yyWantIndent = *--yyIndentStack.end();
        yyIndentStack.pop_back();
      }
    }

and then 

    "("                    { pushIndent(); return TLPAREN; }
    ")"                    { popIndent();  return TRPAREN; }
    "["                    { pushIndent(); return TLBRACKET; }
    "]"                    { popIndent();  return TRBRACKET; }
    "{"                    { pushIndent(); return TLBRACE; }
    "}"                    { popIndent();  return TRBRACE; }

This doesn't cover everything, e.g. `    instanceFunc x = case x of \n[...]`, but that can be solved with some extra parens around the body, and a more comprehensive solution would seem to require a bigger rewrite of the parsing logic.

**Comment by kthielen** [comment]
These are good suggestions.  As usual, the parser is a neglected part of this compiler project.  I will take a look at applying your suggestions tonight.  Thank you for looking at it, the lack of multi-line instance defs has been a pain for me too.

**Comment by kthielen** [comment]
That was a really nice one, I'm embarrassed to say how many times I've hacked around it.  I opened a PR basically copying your code.

The parser definitely deserves some more attention.  This is a great little fix in the meantime.  :)

**Comment by kthielen** [comment]
Merged, thanks adam!
