### ISSUE TITLE
README compilation example

### ISSUE THREAD

**Issue by skaller** [Morgan-Stanley/hobbes#35]
FYI on OSX 10.12 this worked for me:

```
clang++ -std=c++11 test.cpp -o test -lhobbes -lz -lncurses -L/usr/local/lib `llvm-config --libs x86asmparser x86codegen x86 mcjit passes`
```

Changes from documented command line: OSX does not require -ldl. 
I did not have libtinfo, but libncurses worked. 
My hobbes and LLVM are in /usr/local. Not quite sure why clang++ finds
stuff in /usr/local/include.

[Of course I get hundreds of lines of these warnings:
```
ld: warning: direct access in function 'replaceSubString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, llvm::StringRef, llvm::StringRef)' from file '/usr/local/lib/libLLVMAnalysis.a(ScalarEvolution.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes.a(funcdefs.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```
]

**Comment by skaller** [comment]
FYI: 

https://stackoverflow.com/questions/36567072/why-do-i-get-ld-warning-direct-access-in-main-to-global-weak-symbol-in-this

IMHO: this one is a bug in libc++. However it may be possible to suppress it with -fvisibility=default switch when compiling hobbes libraries, not sure how to so that. Sigh.

**Comment by kthielen** [comment]
Thank you for the notes.  I haven't seen this ld warning before, that would have annoyed me too.  If I can reproduce it, I will try your suggestion.

**Comment by skaller** [comment]
So much for computers being deterministic :)

I get this error (also on string class related issue) in my own system build. However with the build of the test case for hobbes, I get *hundreds* of lines the same error. It's not just annoying, I can't even scroll back in the console to find the first one. Both the LLVM and hobbes builds are pretty standard cmake/make operations.

But look:

```
ld: warning: direct access in function 'llvm::sys::getDefaultTargetTriple()' 
from file '/usr/local/lib/libLLVMSupport.a(Host.cpp.o)' 
to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' 
from file '/usr/local/lib/libhobbes.a(funcdefs.C.o)' 
means the weak symbol cannot be overridden at runtime. 
This was likely caused by different translation units being compiled 
with different visibility settings.
```

See the error is in LLVM access to the C++ standard library being hijacked by Hobbes.
Hobbes somehow makes a global weak symbol "eq(char,char)" and LLVM is binding
to it. The "overridden at run time" means this: shared libraries have definitions of and internal
references to symbols, typically "autogenerated" C++ templates. When the shared library
is loaded, one of them is picked, and the others discarded, and the references 
in all the libraries go to that symbol. The linker has to "patch" the code to do this.
(Of course the code uses indirection, and its patching tables). When a new shared library
is loaded, it refers to the already selected symbol, and its own copy is ignored.

However if one library has a "strong" symbol that takes precedence, and the binding
within the library to it cannot be patched (because it isn't indirected through the
relocation table but is a direct reference). So the way I read it, hobbes is auto-instantiating
a C++ template which instantiates the one in question above, but it is being given
a strong property which is not compatible with the rest of the system.

The problem is roughly that C++ "stupidly" insists on certain things being unique,
so hard equality tests are required. Eg between function pointers. And the stupid use
of pointer equality in exception handling (which is not the fault of C++ but the
implementors).

This problem of global uniqueness also impacts global variables.
See also my comments on reentrancy. Same issue. Global variables require
unique addresses across dynamic loading.

**Comment by skaller** [comment]
BTW: could we perhaps have a specific issue thread to deal with linkage issues?

**Comment by kthielen** [comment]
Absolutely
