### ISSUE TITLE
llvm assertion

### ISSUE THREAD

**Issue by adam-antonik** [Morgan-Stanley/hobbes#358]
Calling recordColumns twice like this produces a failure

    > a = {a=1}
    > recordColumns([a])
    ["1"]
    > recordColumns([a])
    hi: /usr/lib/llvm-6.0/include/llvm/IR/GlobalVariable.h:135: llvm::Constant* llvm::GlobalVariable::getInitializer(): Assertion `hasInitializer() && "GV doesn't have initializer!"' failed.
    Aborted

**Comment by kthielen** [comment]
Thanks adam, fix here:
https://github.com/Morgan-Stanley/hobbes/pull/359

I should test with llvm 6 more often, it looks like this doesn't happen on earlier versions.

**Comment by kthielen** [comment]
Fix merged to master, thank you adam!
