### ISSUE TITLE
Linkage Issues

### ISSUE THREAD

**Issue by skaller** [Morgan-Stanley/hobbes#41]
General discussion of issues related to linkage.

This command on OSX 10.12 appears to create a hobbes shared library:
```
clang++ -shared -Wl,-all_load /usr/local/lib/libhobbes-pic.a -WL,-noall_load -L/usr/local/lib `llvm-config --libs x86asmparser x86codegen x86 mcjit passes` -lz -lncurses -o hob.dylib
```
which at least works with the README test code. My LLVM is in /usr/local. The command is converting the already installed libhobbes-pic.a into a local shared library hob.dylib which i later install as /usr/local/lib/libhobbes_dynamic.dylib. Note, I like to use a distinct basename from the static lib, to be absolutely sure when linking i get the library I want (that is, never install *.a and *.dylib with the same basename, the linker is too smart).

When I run the link command above I also get this:
```
ld: warning: direct access in function '(anonymous namespace)::DataFlowSanitizer::addGlobalNamePrefix(llvm::GlobalValue*)' from file '/usr/local/lib/libLLVMInstrumentation.a(DataFlowSanitizer.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'llvm::DOTGraphTraits<llvm::SelectionDAG*>::getNodeAttributes(llvm::SDNode const*, llvm::SelectionDAG const*)' from file '/usr/local/lib/libLLVMSelectionDAG.a(SelectionDAGPrinter.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'llvm::CodeViewDebug::getFullFilepath(llvm::DIFile const*)' from file '/usr/local/lib/libLLVMAsmPrinter.a(CodeViewDebug.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'llvm::CodeViewDebug::getFullFilepath(llvm::DIFile const*)' from file '/usr/local/lib/libLLVMAsmPrinter.a(CodeViewDebug.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'llvm::CodeViewDebug::getFullFilepath(llvm::DIFile const*)' from file '/usr/local/lib/libLLVMAsmPrinter.a(CodeViewDebug.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'llvm::ScalarEvolution::verify() const' from file '/usr/local/lib/libLLVMAnalysis.a(ScalarEvolution.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'llvm::ScalarEvolution::verify() const' from file '/usr/local/lib/libLLVMAnalysis.a(ScalarEvolution.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'replaceSubString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, llvm::StringRef, llvm::StringRef)' from file '/usr/local/lib/libLLVMAnalysis.a(ScalarEvolution.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'llvm::getPGOFuncNameVarName(llvm::StringRef, llvm::GlobalValue::LinkageTypes)' from file '/usr/local/lib/libLLVMProfileData.a(InstrProf.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'llvm::getPGOFuncNameVarName(llvm::StringRef, llvm::GlobalValue::LinkageTypes)' from file '/usr/local/lib/libLLVMProfileData.a(InstrProf.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function '(anonymous namespace)::hasObjCCategoryInModule(llvm::BitstreamCursor&)' from file '/usr/local/lib/libLLVMBitReader.a(BitcodeReader.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function '(anonymous namespace)::hasObjCCategoryInModule(llvm::BitstreamCursor&)' from file '/usr/local/lib/libLLVMBitReader.a(BitcodeReader.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'llvm::sys::getDefaultTargetTriple()' from file '/usr/local/lib/libLLVMSupport.a(Host.cpp.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/usr/local/lib/libhobbes-pic.a(cmodule.C.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```
Now I get this:

```
otool -L hob.dylib
hob.dylib:
	hob.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
This is NOT what I expected! There are no dependencies on LLVM there.
Turns out I didn't build LLVM as a shared lib. Grrr.

**Comment by skaller** [comment]
Right so now it seems clean:

1. Build, link, and install LLVM on OSX *as a shared library*. 
```
cmake -DLLVM_TARGETS_TO_BUILD=host -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_EH=ON -DLLVM_BUILD_LLVM_DYLIB=ON ../llvm-4.0.1.src
sudo make install
```

2. Build and install hobbes (patched for LLVM 4.0).

3. Make a shared library for hobbes:

```
~/Desktop/hobbes>clang++ -shared -Wl,-all_load /usr/local/lib/libhobbes-pic.a -WL,-noall_load -L/usr/local/lib -lLLVM  -lz -lncurses -o hob.dylib
~/Desktop/hobbes>otool -L hob.dylib
hob.dylib:
	hob.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libLLVM.dylib (compatibility version 1.0.0, current version 4.0.1)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
Install it with 
```
sudo cp hob.dylib /usr/local/lib/libhobbes_dynamic.dylib
```

With this setup, all the nasty linker errors are gone. LLVM is shared lib, hobbes is a shared lib.

DO NOT use llvm-config, its bugged.
```
~/Desktop/hobbes>llvm-config --link-shared
llvm-config: error: libLLVM-4.0.dylib is missing
```
Its right, the name of the library installed is libLLVM.dylib.

**Comment by kthielen** [comment]
This is awesome, great work slogging through it!  :)

I think that we should keep this issue open until your notes are added to a build doc and also maybe we can incorporate your approach into the project cmake script.

I like your convention to avoid punning static and dynamic library names, too.

**Comment by skaller** [comment]
I agree, keep it open. Verification from several other developers would be good.
I think it is worth the effort, I like what i have seen of hobbes.
Its unusual for a *commercial* language product's developers to actually pay attention to theory.
You've probably heard this one but I'll tell it anyhow:

An American and a Frenchman are discussing a software project.
The American says "Well, it works in practice!"
To which the Frenchman replies "Ah, but does it work in theory?"

Yes, I heard it on the Ocaml mailing list :)

For me there's another good point: because it's C++ (anyone that can design
a language this good and implement it in C++ is a genius!) and embeddable, 
I can use it in my own system which is specifically designed to be a high level language which
is able to utilise existing C++ codes. I have more questions about creating a
more complete binding: the README is a very good introduction but obviously
not complete documentation. 

The binding will be a good critique of hobbes because Felix has some strict rules 
about how things have to be done.

For example there is a rule types for which you have values must be first class.
[Copyable etc etc in C++ terms] Another rule is that (apart from instrumentation),
functions may not have side effects. If you want side effects you have to use
a procedure. (You do not want to see the Posix bindings!) 
Also Felix does not have exceptions (you can throw them but they always 
terminate the program). So exceptions in C++ code have
to be translated to variants if you want to handle them.

Actually, given the purpose of hobbes, Felix coroutine concepts could be
interesting: perhaps better suited to what you're doing than pure functional
programming. Coroutines handles streams naturally. But this is for down
the track (after my book is more complete :)

**Comment by jeb2239** [comment]
I think this question is related to linkage so I will ask it here. I had made some significant progress with statically compiling hobbes with only trivial changes to the code base to convert hi -> hc , one issue I am having is dealing with bound functions that are given different names from their C function names. It will be necessary for sure to link in a library to run any hobbes binary but ideally we can reuse the same functions used by the programs executed by the jit. This can only be done if the hobbes name is equal to the extern "C" name of the function.

**Comment by kthielen** [comment]
Hey jeb, good to hear from you!  I am not sure if that issue is related but maybe it would be worth filing under an issue that's about your main goal, to support AOT compilation?  Are you thinking that maybe there should be a way to bind symbols such that the binding works either for AOT compilation or JIT compilation?  I can see how the existing JIT binding method would frustrate that effort -- though having C++ type inference take care of most of the type-description details for bound symbols is really convenient.

**Comment by kthielen** [comment]
Closing this issue as we aren't actively working on this problem and we don't have the linkage issues mentioned.  If anyone is going to work on this, please feel free to reopen.  Perhaps we can make this a moot point in a few months.
